# Generated by Django 3.1.1 on 2020-09-09 13:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Branch_name', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='College',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('College_name', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Section_name', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('roll_number', models.CharField(blank=True, max_length=255, null=True)),
                ('Branch_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='details.branch')),
                ('College_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='details.college')),
                ('Section_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='details.section')),
            ],
        ),
    ]
