# Generated by Django 3.1.1 on 2020-09-10 05:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('details', '0003_auto_20200910_1034'),
    ]

    operations = [
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(blank=True, max_length=255, null=True)),
                ('Qualification', models.CharField(blank=True, max_length=255, null=True)),
                ('Work_Experience', models.IntegerField(blank=True, max_length=50, null=True)),
                ('Specialization', models.CharField(blank=True, max_length=255, null=True)),
                ('Branch_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='details.branch')),
                ('College_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='details.college')),
            ],
        ),
    ]
