# Generated by Django 3.1.1 on 2020-09-10 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('details', '0004_faculty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faculty',
            name='Work_Experience',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
