# Generated by Django 3.1.1 on 2020-09-10 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('details', '0005_auto_20200910_1051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faculty',
            name='Work_Experience',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
