# Generated by Django 3.1.1 on 2020-09-10 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('details', '0006_auto_20200910_1100'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faculty',
            name='Name',
        ),
        migrations.AddField(
            model_name='faculty',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
