# Generated by Django 3.1.1 on 2020-09-10 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('details', '0009_auto_20200910_1106'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faculty',
            name='Faculty_name',
        ),
        migrations.AddField(
            model_name='faculty',
            name='name',
            field=models.CharField(blank=True, default='no', max_length=255, null=True),
        ),
    ]
