# Generated by Django 3.1.1 on 2020-09-10 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('details', '0013_auto_20200910_1425'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faculty',
            name='Faculty_name',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
