# Generated by Django 3.1.1 on 2020-09-11 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('details', '0015_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='First_name',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='Last_name',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='Middle_name',
        ),
    ]
